package main

import (
	"os"
	"os/exec"
	"strings"
)

func main() {
	cmd := exec.Command("git", "describe", "--tags")
	ret, err := cmd.Output()
	dist_version := os.Getenv("DIST_VERSION")

	if err != nil || strings.TrimSpace(dist_version) == "" {
		panic("Couldn't read git tags or environment variable to embed version number")
	}

	version := strings.TrimSpace(string(ret))

	if strings.TrimSpace(dist_version) != "" {
		version = strings.TrimSpace(dist_version)
	}

	out, _ := os.Create("version.go")
	defer out.Close()

	out.Write([]byte("package main\n\n//THIS FILE IS AUTOMATICALLY GENERATED BY `go generate` DO NOT EDIT!\n\nvar version=\""))
	out.Write([]byte(version))
	out.Write([]byte("\"\n"))
}
